# name，也就是当前 workflow 的名称
name: publish-stylelint-config

# 下文的意思是：当监听到tag的变更时，执行脚本，比如我们在 github 内新建一个tag
on:
  push:
    tags:
      - 'v*'

# jobs 也就是任务的意思
jobs:
  docs_and_publish:
    # name: 在 Github 中显示的 job 名称
    name: buildLibrary
    runs-on: ubuntu-latest
    steps:
      # name:  当前 step 的名字
      - name: Checkout    # 获取分支的代码和提交记录
        uses: actions/checkout@v2

      - name: Setup Node.js v16.x # 设置 Node.js 的环境
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
 
      - name: Publish to NPM  # 推送到 NPM 上
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
